### ISSUE TITLE
pywt has no attribute dwt 

### ISSUE THREAD

**Issue by imohamadhoseins** [VivekPa/AIAlpha#14]
hi , in preprocess.py i have this following error : 
pywt module has no attribute dwt ()

**Comment by danizil** [comment]
Had the same problem. 
There are two python packages called pywt, the one named pywt being the wrong one...
First you need to pip uninstall pywt and then install pywavelets.
I did it the other way around: first installing pywavelets and things also got jammed. in this case you need to uninstall both and then install pywavelets.
In order to import you need to "import pywt" as you did before.
Happy piping

**Comment by VivekPa** [comment]
Hi, I have removed the usage of pywt in this version due to the bugs in running the modules.
