### ISSUE TITLE
CSV not found error?

### ISSUE THREAD

**Issue by RioChan** [VivekPa/AIAlpha#15]
Hi Champs:

I'm in the last miles to get it done.
May you guide me how to solve the CSV not found error?
Thanks.

BR Rio

rio@ubuntu:/opt/tensorflow/tensorflow/models/research$ python3 AIAlpha/run.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "AIAlpha/run.py", line 8, in <module>
    dataset, average, std = nnmodel(500, 0.01, 0.01)
  File "/opt/tensorflow/tensorflow/models/research/AIAlpha/model_20_encoded.py", line 13, in nnmodel
    train_data = np.array(pd.read_csv("60_return_forex/encoded_return_train_data.csv", index_col=0))
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/local/lib/python3.6/dist-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 387, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 705, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'60_return_forex/encoded_return_train_data.csv' does not exist: b'60_return_forex/encoded_return_train_data.csv'
rio@ubuntu:/opt/tensorflow/tensorflow/models/research$ find . -name "*data.csv"
./AIAlpha/60_return_forex/encoded_return_train_data.csv
./AIAlpha/60_return_forex/return_train_data.csv
./AIAlpha/60_return_forex/return_test_data.csv
./AIAlpha/60_return_forex/encoded_return_test_data.csv
./AIAlpha/features/autoencoded_corrected_data.csv
./AIAlpha/features/autoencoded_data.csv
./AIAlpha/features/autoencoded_train_data.csv
./AIAlpha/features/autoencoded_test_data.csv
./AIAlpha/preprocessing/test_data.csv
./AIAlpha/data_folder/train_data.csv
./AIAlpha/data_folder/training_data.csv
rio@ubuntu:/opt/tensorflow/tensorflow/models/research$

**Comment by dennisdt** [comment]
I believe there is code missing as there is no script to generate the files found in the `forex_y` and `60_return_forex`.

**Comment by oriormeir** [comment]
@VivekPa 
Some of the code appears to be is missing...

**Comment by vilorel** [comment]
So the data folder is completely missing now?

**Comment by VivekPa** [comment]
Hi, yes the data sets were too large to push to github, but the data used was free sample tick data from Tick Data LLC. I don’t know if they still have it on their website though. I can upload a small section of the data if that would help?

**Comment by vilorel** [comment]
@VivekPa thanks for getting back to us. That would be great, yes! Even if you could upload the trimmed down versions of the files, it'd be a great help because then we can just run the quickstart without doing any more work. 
We can also figure out the schema easily, should we decide to plug in our own data and then of course gradually dive into the code. Otherwise, we have to go straight to the code to figure things out...

**Comment by VivekPa** [comment]
Hi, I have uploaded a trimmed version of the data with 1 million rows to play around.

**Comment by vilorel** [comment]
@VivekPa  first of all thanks a lot for uploading the data. I now tried again to run the Quickstart (based on your README) and still got issues because it's looking for a file that doesn't exist.
`sample_data/processed_data/price_bars/dollar_bars.csv`
I guess that the file you uploaded helps but not fully because we still have to sift through all the code to figure out how to connect the dots. Could you please also update the project or the documentation in a way that we could just run it and produce some results? Then we'll take it from there...

**Comment by alfonsrv** [comment]
Project is indeed lacking documentation. Also getting `FileNotFoundError: [Errno 2] No such file or directory: 'data/processed_data/sample_data/processed_data/autoencoder_data/train_x.csv'`
